# Generated by Django 6.0.3 on 2026-04-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clear_direct_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome da sucursal')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código interno')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursais',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='system', editable=False, max_length=30, unique=True)),
                ('default_language', models.CharField(choices=[('pt', 'Português (Moçambique)'), ('en', 'English')], default='pt', max_length=5, verbose_name='Idioma por defeito')),
                ('default_currency', models.CharField(choices=[('MZN', 'Metical (MZN)'), ('USD', 'US Dollar (USD)'), ('ZAR', 'Rand Sul-Africano (ZAR)')], default='MZN', max_length=3, verbose_name='Moeda por defeito')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferência do sistema',
                'verbose_name_plural': 'Preferências do sistema',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='accounts.branch', verbose_name='Sucursais atribuídas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_user_profiles', to='accounts.branch', verbose_name='Sucursal principal'),
        ),
    ]
