# Generated by Django 6.0.3 on 2026-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_branch_systempreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, default='Moçambique', max_length=120, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='branch',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branches/favicons/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='branch',
            name='legal_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome legal'),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branches/logos/', verbose_name='Logotipo'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email do responsável'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone do responsável'),
        ),
        migrations.AddField(
            model_name='branch',
            name='nuit',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NUIT'),
        ),
        migrations.AddField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.CharField(blank=True, max_length=120, verbose_name='Província / estado'),
        ),
        migrations.AddField(
            model_name='branch',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
