# Generated by Django 6.0.3 on 2026-04-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_branch_country_branch_description_branch_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempreference',
            name='patient_code_prefix',
            field=models.CharField(default='PCCP000', max_length=20, verbose_name='Prefixo do ID do paciente'),
        ),
    ]
