# Generated by Django 6.0.3 on 2026-04-09 10:24

import django.db.models.deletion
import re
from django.db import migrations, models


def derive_parent_clinic_name(*candidates):
    for value in candidates:
        if not value:
            continue
        cleaned = re.sub(r"[\s_-]*\d+$", "", value).strip(" -_")
        return cleaned or value.strip() or "Clinic Plus"
    return "Clinic Plus"


def backfill_parent_clinic(apps, schema_editor):
    Clinic = apps.get_model("accounts", "Clinic")
    Branch = apps.get_model("accounts", "Branch")
    Hospital = apps.get_model("clinic", "Hospital")

    if not Branch.objects.exists() and not Hospital.objects.exists():
        return

    clinic = Clinic.objects.order_by("id").first()
    if clinic is None:
        legacy_hospital = Hospital.objects.order_by("id").first()
        first_branch = Branch.objects.order_by("id").first()
        clinic = Clinic.objects.create(
            name=derive_parent_clinic_name(
                getattr(legacy_hospital, "name", ""),
                getattr(first_branch, "name", ""),
            ),
            city=(getattr(legacy_hospital, "city", "") or getattr(first_branch, "city", "")),
            province=(getattr(legacy_hospital, "state", "") or getattr(first_branch, "province", "")),
            country=(getattr(first_branch, "country", "") or "Moçambique"),
            postal_code=(getattr(legacy_hospital, "zip_code", "") or getattr(first_branch, "postal_code", "")),
            address=(getattr(legacy_hospital, "address", "") or getattr(first_branch, "address", "")),
            phone=(getattr(legacy_hospital, "phone", "") or getattr(first_branch, "phone", "")),
            email=(getattr(legacy_hospital, "email", "") or getattr(first_branch, "email", "")),
            logo=getattr(legacy_hospital, "logo", "") or None,
            is_active=True,
        )

    Branch.objects.filter(clinic__isnull=True).update(clinic=clinic)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systempreference_patient_code_prefix'),
        ('clinic', '0006_departamento_branch_medico_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Nome da clínica')),
                ('legal_name', models.CharField(blank=True, max_length=220, verbose_name='Nome legal')),
                ('nuit', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NUIT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/logos/', verbose_name='Logotipo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='clinics/favicons/', verbose_name='Favicon')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('province', models.CharField(blank=True, max_length=120, verbose_name='Província / estado')),
                ('country', models.CharField(blank=True, default='Moçambique', max_length=120, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=30, verbose_name='Código postal')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='accounts.clinic', verbose_name='Clínica'),
        ),
        migrations.RunPython(backfill_parent_clinic, noop_reverse),
    ]
