# Generated by Django 6.0.3 on 2026-04-09 13:05

from django.db import migrations, models


def seed_measurement_units(apps, schema_editor):
    MeasurementUnit = apps.get_model('accounts', 'MeasurementUnit')
    Medicamento = apps.get_model('clinic', 'Medicamento')
    Consumivel = apps.get_model('clinic', 'Consumivel')

    default_units = [
        ("un", "Unidade", "un", "Unidade individual para itens avulsos.", 10),
        ("caixa", "Caixa", "cx", "Embalagem em caixa usada em medicamentos e consumíveis.", 20),
        ("frasco", "Frasco", "fr", "Recipiente fechado para líquidos ou soluções.", 30),
        ("ampola", "Ampola", "amp", "Unidade estéril de dose individual.", 40),
        ("tubo", "Tubo", "tb", "Embalagem tubular para gel, creme ou pomada.", 50),
        ("pacote", "Pacote", "pct", "Conjunto embalado para material clínico ou curativo.", 60),
        ("rolo", "Rolo", "rol", "Formato em rolo para algodão, fita ou materiais semelhantes.", 70),
        ("par", "Par", "par", "Unidade usada para itens que operam aos pares.", 80),
        ("kit", "Kit", "kit", "Conjunto preparado para um procedimento ou tarefa.", 90),
    ]

    for code, name, abbreviation, description, sort_order in default_units:
        MeasurementUnit.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'abbreviation': abbreviation,
                'description': description,
                'sort_order': sort_order,
                'is_active': True,
            },
        )

    existing_codes = set(
        Medicamento.objects.exclude(unidade_medida='').values_list('unidade_medida', flat=True)
    ) | set(
        Consumivel.objects.exclude(unidade_medida='').values_list('unidade_medida', flat=True)
    )

    for code in sorted(code.strip().lower() for code in existing_codes if code):
        MeasurementUnit.objects.get_or_create(
            code=code,
            defaults={
                'name': code.replace('_', ' ').replace('-', ' ').title(),
                'abbreviation': code[:20],
                'description': 'Unidade criada automaticamente a partir dos itens existentes.',
                'sort_order': 100,
                'is_active': True,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clinic_branch_clinic'),
        ('clinic', '0008_consumivel_alter_medicamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Unidade')),
                ('abbreviation', models.CharField(blank=True, max_length=20, verbose_name='Abreviatura')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ('sort_order', 'name', 'code'),
            },
        ),
        migrations.RunPython(seed_measurement_units, noop_reverse),
    ]
