# Generated by Django 6.0.3 on 2026-04-09 14:03

from django.db import migrations, models


def seed_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model("accounts", "PaymentMethod")
    seeds = [
        {
            "code": "cash",
            "name": "Dinheiro",
            "category": "cash",
            "provider": "",
            "description": "Pagamento directo em numerário no caixa.",
            "sort_order": 10,
        },
        {
            "code": "card_pos",
            "name": "Cartão / POS",
            "category": "card",
            "provider": "POS bancário",
            "description": "Cartão bancário processado no terminal POS.",
            "sort_order": 20,
        },
        {
            "code": "bank_transfer",
            "name": "Transferência bancária",
            "category": "bank_transfer",
            "provider": "Banco",
            "description": "Transferência confirmada para conta bancária da clínica.",
            "sort_order": 30,
        },
        {
            "code": "mpesa",
            "name": "M-Pesa",
            "category": "mobile_money",
            "provider": "Vodafone M-Pesa",
            "description": "Carteira móvel amplamente usada no mercado moçambicano.",
            "sort_order": 40,
        },
        {
            "code": "emola",
            "name": "e-Mola",
            "category": "mobile_money",
            "provider": "Movitel",
            "description": "Carteira móvel e-Mola para pagamentos e transferências.",
            "sort_order": 50,
        },
        {
            "code": "mkesh",
            "name": "mKesh",
            "category": "mobile_money",
            "provider": "mKesh",
            "description": "Carteira móvel interoperável no ecossistema moçambicano.",
            "sort_order": 60,
        },
    ]
    for seed in seeds:
        PaymentMethod.objects.update_or_create(
            code=seed["code"],
            defaults={
                "name": seed["name"],
                "category": seed["category"],
                "provider": seed["provider"],
                "description": seed["description"],
                "sort_order": seed["sort_order"],
                "is_active": True,
            },
        )


def unseed_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model("accounts", "PaymentMethod")
    PaymentMethod.objects.filter(
        code__in=["cash", "card_pos", "bank_transfer", "mpesa", "emola", "mkesh"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_measurementunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Método de pagamento')),
                ('category', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão / POS'), ('mobile_money', 'Moeda electrónica'), ('bank_transfer', 'Transferência bancária'), ('other', 'Outro')], default='cash', max_length=30, verbose_name='Categoria')),
                ('provider', models.CharField(blank=True, max_length=120, verbose_name='Provedor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de pagamento',
                'verbose_name_plural': 'Métodos de pagamento',
                'ordering': ('sort_order', 'name', 'code'),
            },
        ),
        migrations.AddField(
            model_name='systempreference',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.RunPython(seed_payment_methods, unseed_payment_methods),
    ]
