# Generated by Django 6.0.3 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_branch_country_branch_description_branch_favicon_and_more"),
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pacientes",
                to="accounts.branch",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pacientes",
                to="clinic.hospital",
            ),
        ),
    ]
