# Generated by Django 6.0.3 on 2026-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_paciente_branch_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='country',
            field=models.CharField(choices=[('Moçambique', 'Moçambique'), ('África do Sul', 'África do Sul'), ('Angola', 'Angola'), ('Botswana', 'Botswana'), ('Brasil', 'Brasil'), ('Cabo Verde', 'Cabo Verde'), ('China', 'China'), ('Estados Unidos', 'Estados Unidos'), ('Eswatini', 'Eswatini'), ('França', 'França'), ('Índia', 'Índia'), ('Malawi', 'Malawi'), ('Portugal', 'Portugal'), ('Reino Unido', 'Reino Unido'), ('Tanzânia', 'Tanzânia'), ('Zâmbia', 'Zâmbia'), ('Zimbabwe', 'Zimbabwe'), ('Outro', 'Outro')], default='Moçambique', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
