# Generated by Django 6.0.3 on 2026-04-08 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systempreference_patient_code_prefix'),
        ('clinic', '0003_paciente_country_alter_paciente_emergency_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('medico', 'Médico'), ('enfermeiro', 'Enfermeiro(a)'), ('laboratorio', 'Laboratório / Técnico'), ('farmacia', 'Farmácia / Stock'), ('recepcao', 'Recepção'), ('administrativo', 'Administrativo'), ('outro', 'Outro')], max_length=20)),
                ('shift_name', models.CharField(blank=True, max_length=120)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('accepts_appointments', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to='accounts.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horário de trabalho',
                'verbose_name_plural': 'Horários de trabalho',
                'ordering': ('weekday', 'start_time', 'user__first_name', 'user__last_name', 'user__username'),
                'constraints': [models.UniqueConstraint(fields=('user', 'branch', 'weekday', 'start_time', 'end_time', 'valid_from'), name='unique_work_schedule_block')],
            },
        ),
    ]
