# Generated by Django 6.0.3 on 2026-04-09 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systempreference_patient_code_prefix'),
        ('clinic', '0004_horariotrabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='clinic.hospital'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='clinic.hospital'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='clinic.hospital'),
        ),
    ]
