# Generated by Django 6.0.3 on 2026-04-09 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systempreference_patient_code_prefix'),
        ('clinic', '0005_agendamento_branch_alter_agendamento_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='medico',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='clinic.departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='clinic.hospital'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_responsavel', to='clinic.medico'),
        ),
    ]
