# Generated by Django 6.0.3 on 2026-04-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_departamento_branch_medico_departamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Clínica legada', 'verbose_name_plural': 'Clínicas legadas'},
        ),
    ]
