# Generated by Django 6.0.3 on 2026-04-09 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_inventory_defaults(apps, schema_editor):
    Branch = apps.get_model('accounts', 'Branch')
    Armazem = apps.get_model('clinic', 'Armazem')
    Medicamento = apps.get_model('clinic', 'Medicamento')
    EstoqueMedicamento = apps.get_model('clinic', 'EstoqueMedicamento')

    def unique_code_for_branch(branch_id):
        base_code = f'ARM-{branch_id:03d}'
        candidate = base_code
        counter = 1
        while Armazem.objects.filter(code=candidate).exists():
            candidate = f'{base_code}-{counter}'
            counter += 1
        return candidate

    default_warehouses = []
    for branch in Branch.objects.all().order_by('id'):
        warehouse, _ = Armazem.objects.get_or_create(
            branch=branch,
            name='Armazém Principal',
            defaults={
                'code': unique_code_for_branch(branch.id),
                'location': 'Base da sucursal',
                'description': 'Armazém criado automaticamente para iniciar o controlo de inventário.',
                'is_active': True,
            },
        )
        default_warehouses.append(warehouse)

    fallback_warehouse = default_warehouses[0] if default_warehouses else None
    if fallback_warehouse is None:
        return

    for medication in Medicamento.objects.filter(quantidade__gt=0):
        if EstoqueMedicamento.objects.filter(medicamento=medication).exists():
            continue
        EstoqueMedicamento.objects.create(
            armazem=fallback_warehouse,
            medicamento=medication,
            quantidade=medication.quantidade,
            stock_minimo=0,
            ponto_reposicao=0,
            observacoes='Stock migrado automaticamente do campo legado quantidade.',
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clinic_branch_clinic'),
        ('clinic', '0007_alter_hospital_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('unidade_medida', models.CharField(blank=True, default='un', max_length=30)),
                ('preco_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumível',
                'verbose_name_plural': 'Consumíveis',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ('name', 'dosagem'), 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AddField(
            model_name='medicamento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='sku',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='unidade_medida',
            field=models.CharField(blank=True, default='un', max_length=30),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=150)),
                ('manager_phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armazens', to='accounts.branch')),
            ],
            options={
                'verbose_name': 'Armazém',
                'verbose_name_plural': 'Armazéns',
                'ordering': ('branch__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EstoqueConsumivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('ponto_reposicao', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('last_counted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_consumiveis', to='clinic.armazem')),
                ('consumivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='clinic.consumivel')),
            ],
            options={
                'verbose_name': 'Stock de consumível',
                'verbose_name_plural': 'Stock de consumíveis',
                'ordering': ('consumivel__name', 'armazem__name'),
            },
        ),
        migrations.CreateModel(
            name='EstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('ponto_reposicao', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('last_counted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_medicamentos', to='clinic.armazem')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='clinic.medicamento')),
            ],
            options={
                'verbose_name': 'Stock de medicamento',
                'verbose_name_plural': 'Stock de medicamentos',
                'ordering': ('medicamento__name', 'armazem__name'),
            },
        ),
        migrations.CreateModel(
            name='MovimentoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('medicamento', 'Medicamento'), ('consumivel', 'Consumível')], max_length=20)),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('stock_before', models.PositiveIntegerField(default=0)),
                ('stock_after', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='clinic.armazem')),
                ('consumivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_inventario', to='clinic.consumivel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_inventario', to='clinic.medicamento')),
            ],
            options={
                'verbose_name': 'Movimento de inventário',
                'verbose_name_plural': 'Movimentos de inventário',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='armazem',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_warehouse_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='estoqueconsumivel',
            constraint=models.UniqueConstraint(fields=('armazem', 'consumivel'), name='unique_consumable_stock_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='estoquemedicamento',
            constraint=models.UniqueConstraint(fields=('armazem', 'medicamento'), name='unique_medication_stock_per_warehouse'),
        ),
        migrations.RunPython(seed_inventory_defaults, noop_reverse),
    ]
