# Generated by Django 6.0.3 on 2026-04-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_pharmacysale_pharmacysaleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysale',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_pharmacy_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pharmacysale',
            name='status',
            field=models.CharField(choices=[('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('returned', 'Devolvida')], default='completed', max_length=20),
        ),
    ]
