from django.urls import path
from . import views

app_name = 'clinic'

urlpatterns = [
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('marcacoes/', views.AppointmentListView.as_view(), name='appointment_list'),
    path('marcacoes/nova/', views.AppointmentCreateView.as_view(), name='appointment_create'),
    path('marcacoes/<int:appointment_pk>/consulta/', views.AppointmentConsultationView.as_view(), name='appointment_consultation'),
    path('agenda/', views.AppointmentAgendaView.as_view(), name='appointment_agenda'),
    path('estrutura/especialidades/', views.SpecialtyListView.as_view(), name='specialty_list'),
    path('estrutura/especialidades/nova/', views.SpecialtyCreateView.as_view(), name='specialty_create'),
    path('estrutura/especialidades/<int:pk>/editar/', views.SpecialtyUpdateView.as_view(), name='specialty_update'),
    path('estrutura/departamentos/', views.DepartmentListView.as_view(), name='department_list'),
    path('estrutura/departamentos/novo/', views.DepartmentCreateView.as_view(), name='department_create'),
    path('estrutura/departamentos/<int:pk>/editar/', views.DepartmentUpdateView.as_view(), name='department_update'),
    path('inventario/', views.InventoryOverviewView.as_view(), name='inventory_overview'),
    path('inventario/armazens/', views.WarehouseListView.as_view(), name='warehouse_list'),
    path('inventario/armazens/novo/', views.WarehouseCreateView.as_view(), name='warehouse_create'),
    path('inventario/armazens/<int:pk>/editar/', views.WarehouseUpdateView.as_view(), name='warehouse_update'),
    path('inventario/medicamentos/catalogo/', views.MedicationCatalogListView.as_view(), name='medication_catalog_list'),
    path('inventario/medicamentos/', views.MedicationListView.as_view(), name='medication_list'),
    path('inventario/medicamentos/novo/', views.MedicationCreateView.as_view(), name='medication_create'),
    path('inventario/medicamentos/<int:pk>/editar/', views.MedicationUpdateView.as_view(), name='medication_update'),
    path('inventario/medicamentos/catalogo/novo/', views.MedicationCatalogCreateView.as_view(), name='medication_catalog_create'),
    path('inventario/medicamentos/catalogo/<int:pk>/editar/', views.MedicationCatalogUpdateView.as_view(), name='medication_catalog_update'),
    path('inventario/consumiveis/catalogo/', views.ConsumableCatalogListView.as_view(), name='consumable_catalog_list'),
    path('inventario/consumiveis/', views.ConsumableListView.as_view(), name='consumable_list'),
    path('inventario/consumiveis/novo/', views.ConsumableCreateView.as_view(), name='consumable_create'),
    path('inventario/consumiveis/<int:pk>/editar/', views.ConsumableUpdateView.as_view(), name='consumable_update'),
    path('inventario/consumiveis/catalogo/novo/', views.ConsumableCatalogCreateView.as_view(), name='consumable_catalog_create'),
    path('inventario/consumiveis/catalogo/<int:pk>/editar/', views.ConsumableCatalogUpdateView.as_view(), name='consumable_catalog_update'),
    path('inventario/movimentos/', views.InventoryMovementListView.as_view(), name='inventory_movement_list'),
    path('inventario/movimentos/novo/', views.InventoryMovementCreateView.as_view(), name='inventory_movement_create'),
    path('horarios/', views.WorkScheduleListView.as_view(), name='work_schedule_list'),
    path('horarios/novo/', views.WorkScheduleCreateView.as_view(), name='work_schedule_create'),
    path('horarios/<int:pk>/', views.WorkScheduleDetailView.as_view(), name='work_schedule_detail'),
    path('horarios/<int:pk>/editar/', views.WorkScheduleUpdateView.as_view(), name='work_schedule_update'),
    path('horarios/<int:pk>/estado/', views.WorkScheduleToggleStatusView.as_view(), name='work_schedule_toggle_status'),
    path('pacientes/', views.PatientListView.as_view(), name='patient_list'),
    path('pacientes/novo/', views.PatientCreateView.as_view(), name='patient_create'),
    path('pacientes/historico/', views.PatientHistoryListView.as_view(), name='patient_history_list'),
    path('pacientes/<int:pk>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('pacientes/<int:pk>/editar/', views.PatientUpdateView.as_view(), name='patient_update'),
    path('pacientes/<int:pk>/ficha-pdf/', views.PatientPdfDownloadView.as_view(), name='patient_pdf'),
    path('pacientes/<int:pk>/estado/', views.PatientToggleStatusView.as_view(), name='patient_toggle_status'),
    path('pacientes/<int:pk>/historico/', views.PatientHistoryDetailView.as_view(), name='patient_history_detail'),
    path('', views.dashboard, name='index'),
]
