from .permissions_view import (
    PermissionCreateView,
    PermissionDetailView,
    PermissionListView,
    PermissionUpdateView,
)
from .preferences_view import (
    BranchSwitchView,
    LanguageSwitchView,
    MeasurementUnitCreateView,
    MeasurementUnitListView,
    MeasurementUnitUpdateView,
    SystemPreferenceView,
)
from .organization_view import (
    BranchCreateView,
    BranchDetailView,
    BranchListView,
    BranchToggleStatusView,
    BranchUpdateView,
    ClinicCreateView,
    ClinicDetailView,
    ClinicListView,
    ClinicToggleStatusView,
    ClinicUpdateView,
)
from .roles_view import (
    RoleCreateView,
    RoleDetailView,
    RoleListView,
    RoleUpdateView,
)
from .users_view import (
    UserCreateView,
    UserDetailView,
    UserListView,
    UserToggleStatusView,
    UserUpdateView,
)

__all__ = [
    "UserListView",
    "UserDetailView",
    "UserCreateView",
    "UserUpdateView",
    "UserToggleStatusView",
    "RoleListView",
    "RoleDetailView",
    "RoleCreateView",
    "RoleUpdateView",
    "PermissionListView",
    "PermissionDetailView",
    "PermissionCreateView",
    "PermissionUpdateView",
    "BranchListView",
    "BranchDetailView",
    "BranchCreateView",
    "BranchUpdateView",
    "BranchToggleStatusView",
    "ClinicListView",
    "ClinicDetailView",
    "ClinicCreateView",
    "ClinicUpdateView",
    "ClinicToggleStatusView",
    "SystemPreferenceView",
    "MeasurementUnitListView",
    "MeasurementUnitCreateView",
    "MeasurementUnitUpdateView",
    "LanguageSwitchView",
    "BranchSwitchView",
]
